import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Abdul Rafay - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/assets/ARlogo.png" />
        
      </Head>
      <body className={inter.className}>
        <ThemeProvider>
          <div class="relative h-full w-full">
            <div class="relative h-full w-full">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
