
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/context/ThemeProvider";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Abdul Rafay - Portfolio",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon"  href="/vercel.svg" />
      </Head>
      <body className={inter.className}>
        <ThemeProvider >
          <Navbar />
          
          {children}
          <Footer />
        </ThemeProvider>

      </body>
    </html>
  );
}
